name: Continuos Integration and Deployment
on: [push]
env:
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN_GESTION_VUELOS_A }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID_GESTION_VUELOS_A }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_GESTION_VUELOS_A }}
jobs:
  Build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/gestion-de-vuelos-A' || github.ref == 'refs/heads/dev'
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js 20.x 📦
        uses: actions/setup-node@v2
        with:
          node-version: 20.x
      - name: Install dependencies
        run: yarn install
      - name: Build project
        run: yarn build
  Deploy:
    needs: Build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/gestion-de-vuelos-A' || github.ref == 'refs/heads/dev'
    steps:
      - uses: actions/checkout@v2
      - name: Usar NodeJS 20.x
        uses: actions/setup-node@v2
        with:
          node-version: 20.x
      - name: Install Vercel CLI
        run: yarn global add vercel
      - name: Pull Vercel secrets
        run: vercel pull --yes --token=${{secrets.VERCEL_TOKEN_GESTION_VUELOS_A}}
      - name: Trigger Vercel Deployment
        run: vercel deploy --no-wait --token=${{secrets.VERCEL_TOKEN_GESTION_VUELOS_A}}